spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8081/
          predicates:
            - Path= /owners/**
        - id: r2
          uri: http://localhost:8081/
          predicates:
            - Path= /vehicles/**
        - id: r3
          uri: http://localhost:8181/
          predicates:
            - Path= /infractions/**
        - id: r4
          uri: http://localhost:8082/
          predicates:
            - Path= /radars/**